"""add_customer_pii_fields_to_session

Revision ID: e4ef62d0f1cb
Revises: 001
Create Date: 2026-05-13 18:08:24.165936+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4ef62d0f1cb'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analytics_daily', 'total_sessions',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('analytics_daily', 'completed_sessions',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('analytics_daily', 'abandoned_sessions',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('analytics_daily', 'offline_sessions',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('analytics_daily', 'pii_detected_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('analytics_daily', 'ai_suggestion_used',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('analytics_daily', 'ai_suggestion_edited',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('analytics_daily', 'ai_suggestion_ignored',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('analytics_daily', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('analytics_daily', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_analytics_daily_branch_date', table_name='analytics_daily')
    op.alter_column('bilingual_summaries', 'pdf_generated',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('bilingual_summaries', 'whatsapp_sent',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('bilingual_summaries', 'generated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('uq_summary_session', 'bilingual_summaries', type_='unique')
    op.alter_column('branches', 'bank_name',
               existing_type=sa.VARCHAR(length=200),
               server_default=None,
               existing_nullable=False)
    op.alter_column('branches', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('branches', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('exchanges', 'pii_detected',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('exchanges', 'staff_used_suggestion',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('exchanges', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_exchanges_session_exchange', table_name='exchanges')
    op.alter_column('pii_logs', 'detected_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_pii_logs_pii_type', table_name='pii_logs')
    op.alter_column('process_steps', 'speak_to_customer',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('process_steps', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('session_process_tracking', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_tracking_session_id', table_name='session_process_tracking')
    op.drop_index('ix_tracking_step_id', table_name='session_process_tracking')
    op.create_index(op.f('ix_session_process_tracking_session_id'), 'session_process_tracking', ['session_id'], unique=False)
    op.create_index(op.f('ix_session_process_tracking_step_id'), 'session_process_tracking', ['step_id'], unique=False)
    op.add_column('sessions', sa.Column('customer_account_number', sa.String(length=30), nullable=True))
    op.add_column('sessions', sa.Column('customer_mobile_number', sa.String(length=15), nullable=True))
    op.add_column('sessions', sa.Column('customer_name', sa.String(length=200), nullable=True))
    op.add_column('sessions', sa.Column('customer_dob', sa.String(length=20), nullable=True))
    op.add_column('sessions', sa.Column('customer_pan', sa.String(length=20), nullable=True))
    op.add_column('sessions', sa.Column('customer_aadhaar_last4', sa.String(length=4), nullable=True))
    op.add_column('sessions', sa.Column('customer_account_type', sa.String(length=50), nullable=True))
    op.add_column('sessions', sa.Column('customer_kyc_status', sa.String(length=20), nullable=True))
    op.add_column('sessions', sa.Column('customer_balance', sa.String(length=30), nullable=True))
    op.alter_column('sessions', 'staff_language',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sessions', 'entry_method',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sessions', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sessions', 'total_exchanges',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sessions', 'offline_mode',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sessions', 'pii_detected',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_sessions_created_at', table_name='sessions')
    op.alter_column('staff_members', 'role',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('staff_members', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('staff_members', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staff_members', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('staff_members', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('staff_members', 'role',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'teller'::character varying"),
               existing_nullable=False)
    op.create_index('ix_sessions_created_at', 'sessions', ['created_at'], unique=False)
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('sessions', 'pii_detected',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('sessions', 'offline_mode',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('sessions', 'total_exchanges',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('sessions', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'waiting'::character varying"),
               existing_nullable=False)
    op.alter_column('sessions', 'entry_method',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'walk_in'::character varying"),
               existing_nullable=False)
    op.alter_column('sessions', 'staff_language',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("'Hindi'::character varying"),
               existing_nullable=False)
    op.drop_column('sessions', 'customer_balance')
    op.drop_column('sessions', 'customer_kyc_status')
    op.drop_column('sessions', 'customer_account_type')
    op.drop_column('sessions', 'customer_aadhaar_last4')
    op.drop_column('sessions', 'customer_pan')
    op.drop_column('sessions', 'customer_dob')
    op.drop_column('sessions', 'customer_name')
    op.drop_column('sessions', 'customer_mobile_number')
    op.drop_column('sessions', 'customer_account_number')
    op.drop_index(op.f('ix_session_process_tracking_step_id'), table_name='session_process_tracking')
    op.drop_index(op.f('ix_session_process_tracking_session_id'), table_name='session_process_tracking')
    op.create_index('ix_tracking_step_id', 'session_process_tracking', ['step_id'], unique=False)
    op.create_index('ix_tracking_session_id', 'session_process_tracking', ['session_id'], unique=False)
    op.alter_column('session_process_tracking', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.alter_column('process_steps', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('process_steps', 'speak_to_customer',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.create_index('ix_pii_logs_pii_type', 'pii_logs', ['pii_type'], unique=False)
    op.alter_column('pii_logs', 'detected_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_index('ix_exchanges_session_exchange', 'exchanges', ['session_id', 'exchange_number'], unique=False)
    op.alter_column('exchanges', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('exchanges', 'staff_used_suggestion',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('exchanges', 'pii_detected',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('branches', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('branches', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('branches', 'bank_name',
               existing_type=sa.VARCHAR(length=200),
               server_default=sa.text("'Union Bank of India'::character varying"),
               existing_nullable=False)
    op.create_unique_constraint('uq_summary_session', 'bilingual_summaries', ['session_id'])
    op.alter_column('bilingual_summaries', 'generated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('bilingual_summaries', 'whatsapp_sent',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('bilingual_summaries', 'pdf_generated',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.create_index('ix_analytics_daily_branch_date', 'analytics_daily', ['branch_id', 'date'], unique=True)
    op.alter_column('analytics_daily', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('analytics_daily', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('analytics_daily', 'ai_suggestion_ignored',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('analytics_daily', 'ai_suggestion_edited',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('analytics_daily', 'ai_suggestion_used',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('analytics_daily', 'pii_detected_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('analytics_daily', 'offline_sessions',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('analytics_daily', 'abandoned_sessions',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('analytics_daily', 'completed_sessions',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('analytics_daily', 'total_sessions',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    # ### end Alembic commands ###
